### ISSUE TITLE
Output formatting improvements

### ISSUE THREAD

**Issue by djmattyg007** [probablykasper/cpc#20]
Currently the output doesn't produce nice human-readable descriptions, and doesn't differentiate between singular and plural values.

```
❯ target/release/cpc '123 kph'
123 KilometersPerHour

❯ target/release/cpc '1 kph'
1 KilometersPerHour
```

It would be good if the output of the above was `123 kilometres per hour` and `1 kilometre per hour`.

**Comment by probablykasper** [comment]
Would be nice for sure. I think the way to go is implement `fmt::Display` for `Unit`
