### ISSUE TITLE
Negative exponents are calculated incorrectly without parenthesis

### ISSUE THREAD

**Issue by Delta-official** [probablykasper/cpc#37]
As of 1.9.2, cpc incorrectly calculates the sign of negative exponents without parenthesis

|Expression|Result|Expected|
|-|-|-|
|-3^2|9|-9
|\(-3\)^2|9|9

**Comment by probablykasper** [comment]
Hmm it's a bit tricky. `-` may or may not take precedence over `^` depending on it's position:
```
-3^2 == -(3^4)
3^-2 == 3^(-2)
```

**Comment by probablykasper** [comment]
Nevermind, not that tricky. Released the fix in v1.9.3
