### ISSUE TITLE
Inputs need to be quoted

### ISSUE THREAD

**Issue by djmattyg007** [probablykasper/cpc#5]
It doesn't appear to be stated anywhere in the readme, but as far as I can tell the full input query needs to be quoted and passed as a single argument on the shell. This was quite frustrating until I worked it out.

I think the readme should be updated to state this. I also think the examples section of the readme should be updated to include the expected results. This will assist users in testing the program.

**Comment by probablykasper** [comment]
It's not stated anywhere, but the CLI Usage section shows it pretty clearly imo. Might be a good idea to make it freak out if you pass extra arguments

I don't really think it's necessary to add the results to the examples. I don't think most people need to know it, and if you do you might want to check with a third party resource
